platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

pod 'MAGPagedScrollView' , :git => 'https://github.com/EK-MAG/MAGPagedScrollView.git', :commit => '9b1b64900b681de8915c173ba7298a72e6baba53'
pod 'SwiftyJSON'
